action_values: [0, 45, 50, 55]
activation: tanh
batch_size: 256
clip_range: 0.2
delta: 0.05
dim_hidden_layers: [4, 2]
ent_coef: 0.0001
filename: data_price_uni_h_time.csv
gae_lambda: 0.9999
gamma: 0.999
gas_fee: 5
grid: [action_values, learning_rate, dim_hidden_layers, activation]
hyperparameters:
  action_values:
  - - [0, 10, 15, 20]
    - [0, 10, 20, 30]
    - [0, 25, 50]
    - [0, 45, 50, 55]
    - [0, 50, 100]
  - cat
  activation:
  - [relu, tanh, sigmoid]
  - cat
  clip_range:
  - [0.05, 0.1, 0.2, 0.3, 0.4]
  - cat
  dim_hidden_layers:
  - - [4, 2]
    - [6, 2]
    - [8, 2]
    - [10, 2]
    - [4, 4]
    - [6, 4]
    - [8, 4]
    - [10, 4]
    - [8, 8]
    - [10, 8]
    - [4, 4, 4]
    - [6, 6, 6]
  - cat
  ent_coef:
  - [1.0e-05, 0.01, 0.001, 0.0001]
  - cat
  gamma:
  - [0.9, 0.99, 0.999, 0.9999]
  - cat
  learning_rate:
  - [0.01, 0.001, 0.0001, 1.0e-05, 0.005, 0.0005, 5.0e-05]
  - cat
learning_rate: 0.01
ma_window: 10
model_name: ppo_custom_env_20241001_1
model_to_load: ppo_custom_env_20241001
n_trials: 10
num_epochs: 5
pct_split: 0.9
random_sampler: false
seed: 256
target_kl: 0.3
total_timesteps: 1000000
total_timesteps_1: 100000
train_model: false
vf_coef: 0.1
x: 10
